services:
  - type: web
    name: render-hello-world-web
    env: ruby
    branch: main
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb



